
#[s3]
bucketName : ""
accessKey: ""
accessSecret : ""
region: "eu-west-2"

email_region: "eu-west-2"

#
##live
db_name : "lifetrusty_db"

db_pass : ""
db_user : "lifetrusty"
db_type : "postgres"
ssl : "require"
db_host : ""

KEY : ""
db_port : "5000"
token_password : ""



